- name: Install poetry
  ansible.builtin.pip:
    name: poetry

- name: Add commons
  import_tasks: commons.yml
  
- name: Clone automatic_exploit_generation from GitHub
  ansible.builtin.git:
    repo: https://github.com/CyberReasoningSystem/automatic_exploit_generation.git
    dest: /home/{{ username }}/automatic_exploit_generation
    recursive: True

- name: Install automatic_exploit_generation deps
  ansible.builtin.shell: PATH=/home/{{ username }}/.local/bin:$PATH poetry install --no-dev
  args:
    chdir: /home/{{ username }}/automatic_exploit_generation/

- name: Build automatic_exploit_generation docker container
  ansible.builtin.shell: docker build --tag zeratool_lib -f docker/Dockerfile.zeratool_lib .
  args:
    chdir: /home/{{ username }}/automatic_exploit_generation/
    executable: /bin/bash 
  become: yes