---
- hosts: all
  become: yes

  vars:
    username: "vagrant"
    hostname: "opencrs"

  tasks:
  - name: Set the timezone to 'Bucharest'
    file:
      src: /usr/share/zoneinfo/Europe/Bucharest
      dest: /etc/localtime
      state: link

  - name: Install Docker
    import_tasks: docker-install.yml

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes

  - name: Add dataset
    import_tasks: dataset.yml

  #- name: Reboot the machine
    #reboot:

