---
- hosts: all

  vars:
    username: "vagrant"
    hostname: "opencrs"

  tasks:
  - name: Set the timezone to 'Bucharest'
    file:
      src: /usr/share/zoneinfo/Europe/Bucharest
      dest: /etc/localtime
      state: link
    become: yes

  - name: Install Docker
    import_tasks: docker-install.yml

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
    become: yes

  - name: Install the toolchain
    apt:
      name: ['python3.10', 'python3.10-dev']
      state: present
    become: yes

  - name: Add dataset
    import_tasks: dataset.yml

  - name: Add attack surface approximation
    import_tasks: attack-surface-approximation.yml

  - name: Add vulnerability_analytics
    import_tasks: vulnerability_analytics.yml

  - name: Add automatic_exploit_generation
    import_tasks: automatic_exploit_generation.yml 

  - name: Add wiki
    import_tasks: wiki.yml

  - name: Add opencrs_dataset
    import_tasks: opencrs_dataset.yml
  
  - name: Add zeratool_lib
    import_tasks: zeratool_lib.yml
  
  - name: Add awesome_binary_analysis
    import_tasks: awesome_binary_analysis.yml

  - name: Add nist_c_test_suite
    import_tasks: nist_c_test_suite.yml
  
  - name: Add signature_generation
    import_tasks: signature_generation.yml

  #- name: Reboot the machine
    #reboot:

