- name: Install poetry
  ansible.builtin.pip:
    name: poetry

- name: Add commons
  import_tasks: commons.yml

- name: Clone vulnerability_analytics from GitHub
  ansible.builtin.git:
    repo: https://github.com/CyberReasoningSystem/vulnerability_analytics.git
    dest: /home/{{ username }}/vulnerability_analytics
    recursive: True

- name: Install vulnerability_analytics deps
  ansible.builtin.shell: PATH=/home/{{ username }}/.local/bin:$PATH poetry install --no-dev
  args:
    chdir: /home/{{ username }}/vulnerability_analytics/

# - name: Build vulnerability_analytics docker container
#   ansible.builtin.shell: docker build . -t vulnerability_analytics:1.0.0-alpha -f ./docker/Dockerfile
#   args:
#     chdir: /home/{{ username }}/vulnerability_analytics/
#     executable: /bin/bash 
#   become: yes